distspecversion: 1.0.1
http:
  address: 0.0.0.0
  port: 5000
storage:
  rootdirectory: /var/lib/zot/data
  gc: true
  retention:
    delay: 6h
    policies:
      - repositories:
          - "**"
        deleteReferrers: true
        deleteUntagged: true
        keepTags:
          - mostRecentlyPushedCount: 5
            mostRecentlyPulledCount: 5
            pulledWithin: 168h # 7 days
            pushedWithin: 168h # 7 days
extensions:
  search:
    enable: true
  ui:
    enable: true
  sync:
    registries:
      - urls:
        - https://ghcr.io
        - https://registry-1.docker.io
        - https://quay.io
        - https://k8s.gcr.io
        - https://gcr.io
        onDemand: true
        tlsVerify: true
        maxRetries: 3
        retryInterval: "30s"
        content:
          - prefix: "**"
            destination: "/proxy"
