name: Build Image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    # Weekly at 00:00 on Monday
    - cron: '0 0 * * 1'

permissions:
  contents: read
  actions: read
  id-token: write
  packages: write

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: rsturla-homelab/bootc-centos-base/.github/workflows/_build.yml@main
    secrets: inherit
    with:
      image-name: bootc/qemu/oci-registry
      os-version: stream10
      base-image-name: centos-base-qemu-stream10
